apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-exchange-service-deployment
spec:
  replicas: 3 # Adjust as needed
  selector:
    matchLabels:
      app: second-exchange-service
  template:
    metadata:
      labels:
        app: second-exchange-service
    spec:
      containers:
      - name: second-exchange-service
        image: cdchandani/second-exchange-service-img1:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKER
          value: kafka-service:9092
        - name: REDIS_HOST
          value: redis-service:6379
---
apiVersion: v1
kind: Service
metadata:
  name: second-exchange-service
spec:
  selector:
    app: second-exchange-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
